insert into menus (menu_nombre,menu_precio) values ("lunes normal",9.00);
insert into menus (menu_nombre,menu_precio) values ("martes normal",9.00);
insert into menus (menu_nombre,menu_precio) values ("miercoles normal",9.00);
insert into menus (menu_nombre,menu_precio) values ("jueves normal",9.00);
insert into menus (menu_nombre,menu_precio) values ("viernes normal",9.00);
insert into menus (menu_nombre,menu_precio) values ("lunes especial",15.00);
insert into menus (menu_nombre,menu_precio) values ("martes especial",15.00);
insert into menus (menu_nombre,menu_precio) values ("miercoles especial",15.00);
insert into menus (menu_nombre,menu_precio) values ("jueves especial",15.00);
insert into menus (menu_nombre,menu_precio) values ("viernes especial",15.00);
insert into platos (plato_nombre,plato_calorias) values ("lentejas",100);
insert into platos (plato_nombre,plato_calorias) values ("judias verdes",80);
insert into platos (plato_nombre,plato_calorias) values ("arroz blanco",50);
insert into platos (plato_nombre,plato_calorias) values ("paella",80);
insert into platos (plato_nombre,plato_calorias,plato_cuchara) values ("sopa de pescado",50,true);
insert into platos (plato_nombre,plato_calorias,plato_cuchara) values ("caldo de carne",75,true);
insert into platos (plato_nombre,plato_calorias) values ("cocido",150);
insert into platos (plato_nombre,plato_calorias) values ("fabes",100);
insert into platos (plato_nombre,plato_calorias) values ("ternera en salsa",75);
insert into platos (plato_nombre,plato_calorias) values ("dorada a la sal",40);
insert into platos (plato_nombre,plato_calorias) values ("salmon",50);
insert into platos (plato_nombre,plato_calorias) values ("lomo de cerdo",50);
insert into platos (plato_nombre,plato_calorias) values ("entrecot",75);
insert into platos (plato_nombre,plato_calorias) values ("lubina",60);
insert into platos (plato_nombre,plato_calorias) values ("trucha",50);
insert into platos (plato_nombre,plato_calorias) values ("pulpo a feira",50);
insert into platos (plato_nombre,plato_calorias) values ("mero",40);
insert into platos (plato_nombre,plato_calorias) values ("chuletas de cerdo",50);
insert into platos (plato_nombre,plato_calorias) values ("chuletas de cordero",50);
insert into platos (plato_nombre,plato_calorias) values ("huevos rotos",30);
insert into platos (plato_nombre,plato_calorias) values ("flan con nata",15);
insert into platos (plato_nombre,plato_calorias) values ("yogurt",10);
insert into platos (plato_nombre,plato_calorias) values ("tarta de queso",25);
insert into platos (plato_nombre,plato_calorias) values ("cafe",5);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",1,1);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",1,2);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",1,3);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",1,4);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",2,1);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",2,2);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",2,3);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",2,4);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",3,4);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",3,5);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",3,6);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",3,7);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",4,4);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",4,5);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",4,6);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",4,7);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",5,1);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",5,2);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",5,6);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",5,7);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",6,1);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",6,2);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",6,3);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",6,4);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",7,1);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",7,2);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",7,3);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",7,4);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",8,4);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",8,5);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",8,6);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",8,7);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",9,4);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",9,5);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",9,6);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",9,7);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",10,1);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",10,2);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",10,6);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("primero",10,7);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",1,9);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",1,10);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",1,11);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",1,12);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",2,13);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",2,14);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",2,15);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",2,16);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",3,17);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",3,18);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",3,19);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",3,20);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",4,10);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",4,11);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",4,12);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",4,13);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",5,14);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",5,15);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",5,16);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",5,17);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",6,18);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",6,19);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",6,20);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",6,9);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",7,10);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",7,11);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",7,12);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",7,13);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",8,14);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",8,15);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",8,16);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",8,17);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",9,18);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",9,19);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",9,20);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",9,17);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",10,11);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",10,12);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",10,16);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("segundo",10,17);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",1,21);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",1,22);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",2,23);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",2,24);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",3,21);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",3,22);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",4,23);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",4,24);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",5,21);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",5,22);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",6,23);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",6,24);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",7,21);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",7,22);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",8,23);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",8,24);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",9,21);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",9,22);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",10,23);
insert into menus_platos (mp_tipo,menu_id,plato_id) values ("postre",10,24);
insert into ingredientes (plato_id,ingrediente_nombre) values (1,"lentejas");
insert into ingredientes (plato_id,ingrediente_nombre) values (1,"chorizo");
insert into ingredientes (plato_id,ingrediente_nombre) values (2,"judias blancas");
insert into ingredientes (plato_id,ingrediente_nombre) values (2,"chorizo");
insert into ingredientes (plato_id,ingrediente_nombre) values (2,"laurel");
insert into ingredientes (plato_id,ingrediente_nombre) values (3,"arroz");
insert into ingredientes (plato_id,ingrediente_nombre) values (4,"arroz");
insert into ingredientes (plato_id,ingrediente_nombre) values (4,"pollo");
insert into ingredientes (plato_id,ingrediente_nombre) values (4,"marisco");
insert into ingredientes (plato_id,ingrediente_nombre) values (5,"pescado");
insert into ingredientes (plato_id,ingrediente_nombre) values (5,"avecrem");
insert into ingredientes (plato_id,ingrediente_nombre) values (6,"carne");
insert into ingredientes (plato_id,ingrediente_nombre) values (6,"avecrem");
insert into ingredientes (plato_id,ingrediente_nombre) values (7,"garbanzos");
insert into ingredientes (plato_id,ingrediente_nombre) values (7,"falda");
insert into ingredientes (plato_id,ingrediente_nombre) values (7,"chorizo");
insert into ingredientes (plato_id,ingrediente_nombre) values (7,"gallina");
insert into ingredientes (plato_id,ingrediente_nombre) values (8,"alubias pintas");
insert into ingredientes (plato_id,ingrediente_nombre) values (8,"chorizo");
