DECLARE
    BONUS NUMBER;
BEGIN
    BONUS:=5;
    CASE
        WHEN BONUS > 500 THEN DBMS_OUTPUT.PUT_LINE('Excelente!!');
        WHEN BONUS <=500 AND BONUS >250 THEN DBMS_OUTPUT.PUT_LINE('Muy bien!!');
        WHEN BONUS <=250 AND BONUS >100 THEN DBMS_OUTPUT.PUT_LINE('Bien!!');
        ELSE DBMS_OUTPUT.PUT_LINE('Eres pobre');
    END CASE;
END;
