/*
También existen algunos funciones o métodos
como java.
*/
DECLARE
    EJEMPLO VARCHAR(45):='Esto es un eJeMpLo';
    CORTAR EJEMPLO%TYPE;
    MAYUSCULA EJEMPLO%TYPE;
    MINUSCULA EJEMPLO%TYPE;
    NUM NUMBER := 22.9;
BEGIN
    DBMS_OUTPUT.PUT_LINE(EJEMPLO);
    CORTAR:= SUBSTR(EJEMPLO,12,7);
    DBMS_OUTPUT.PUT_LINE(CORTAR);
    MAYUSCULA:=UPPER(CORTAR);
    DBMS_OUTPUT.PUT_LINE(MAYUSCULA);
    MINUSCULA:=LOWER(CORTAR);
    DBMS_OUTPUT.PUT_LINE(MINUSCULA);
    DBMS_OUTPUT.PUT_LINE(FLOOR(NUM));
END;

